# Generated by Django 4.0 on 2021-12-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='emailClient',
            field=models.EmailField(max_length=254),
        ),
    ]
