# Generated by Django 4.0 on 2021-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientApp', '0002_alter_clients_emailclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('passWord', models.CharField(max_length=20)),
                ('Token', models.IntegerField()),
            ],
        ),
    ]
